# Generated by Django 5.1.6 on 2025-02-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='identifier',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
