# Generated by Django 5.1.6 on 2025-02-22 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_parent_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('text', 'Text'), ('pdf', 'PDF')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='assignment',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='assignments/'),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='fee_status',
            field=models.CharField(choices=[('not_paid', 'Not Paid'), ('partially_paid', 'Partially Paid'), ('fully_paid', 'Fully Paid')], default='not_paid', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10)),
                ('period', models.IntegerField(help_text='Enter the period number (e.g., 1, 2, 3, etc.)')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='portal.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='portal.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetables', to='portal.teacher')),
            ],
        ),
    ]
